Cambio de textos a español y formato de salida de printf a echo

diff --git a/installDots b/installDots
--- a/installDots
+++ b/installDots
@@ -7,39 +7,77 @@
 # Modifier: allenmagic
 #	raw_url: https://github.com/gh0stzk
 # modifi_url: https://github.com/allenmagic
+### ---------- Basicos scripts ---------- ### 
+ 
+green="\e[0;32m\033[1m"           # Correct message
+red="\e[0;31m\033[1m"             # Failed message
+blue="\e[0;34m\033[1m"            # Normal message
+yellow="\e[0;33m\033[1m"          # Warning message
+purple="\e[0;35m\033[1m"          # Resalto de variable
+turquoise="\e[0;36m\033[1m"
+gray="\e[0;37m\033[1m"            # Color normal
+end="\033[0m\e[0m"                # Final de color
 
+trap ctrl_c INT
 
-CRE=$(tput setaf 1)
-CYE=$(tput setaf 3)
-CGR=$(tput setaf 2)
-CBL=$(tput setaf 4)
-BLD=$(tput bold)
-CNC=$(tput sgr0)
+function ctrl_c(){
+    echo -e "${Red}[!]${gray} Exiting...${end}\n"
+    tput cnorm
+    exit 0
+}
+ 
+function logo () {
+# Letra "Calvin S" de https://www.freetool.dev/es/generador-de-letras-ascii
+clear
+echo -e "
+╔╗ ┌─┐┬ ┌┬┐┌─┐┬─┐╔═╗┌─┐┬─┐┬┌─┐┌┬┐┌─┐
+╠╩╗│ ││  │ ├┤ ├┬┘╚═╗│  ├┬┘│├─┘ │ └─┐
+╚═╝└─┘┴─┘┴ └─┘┴└─╚═╝└─┘┴└─┴┴   ┴ └─┘
+                        ${turquoise}By Boltercio${end}
+"
+}
+ 
+function CheckUser() {
+if [ $UID != 0 ]; then
+    echo -e "${red}[!]${gray} This script must be run with root permissions${end}"
+    while true; do
+        echo -e "${yellow}[*]${gray} You want execute this script with sudo command? ${turquoise}[Y/n]${end}"
+        read response
+        case $response in
+            [yY]* ) echo -e "${green}[+]${gray} Launching script with sudo permissions.${end}"
+            sudo ./$0
+            break;;
+            [nN]* ) echo -e "${red}[!]${gray} Script canceled by user.${end}"
+            break;;
+            *) echo -e "${red}[!]${gray} invalid input.${end}";;
+        esac
+    done
+    exit 0
+fi
+} 
 
 backup_folder=~/.RiceBackup
 date=$(date +%Y%m%d-%H%M%S)
 
-logo () {
-	
-	local text="${1:?}"
-	echo -en "z0mbi3 Dotfiles\n\n"
-    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
-}
-
 ########## ---------- You must not run this as root ---------- ##########
 
 if [ "$(id -u)" = 0 ]; then
-    echo "This script MUST NOT be run as root user."
+    echo "Este script NO DEBE ejecutarse como root."
     exit 1
 fi
 
 ########## ---------- Welcome ---------- ##########
 
-logo "Welcome!"
-printf '%s%sThis script will check if you have the necessary dependencies, \n1. and if not, it will install them. \n2. And then ,it will clone the RICE in your HOME directory.\n3. After that, it will create a secure backup of your files, \n4. and then copy the new files to your computer.\n\nMy dotfiles DO NOT modify any of your system configurations.\nYou will be prompted for your root password to install missing dependencies and/or to switch to zsh shell if its not your default.\n\nThis script doesnt have the potential power to break your system, it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" "${CRE}" "${CNC}"
+logo 
+echo -e "${gray}Bienvenido!!${end}"
+echo -e "${red}Este script comprobara si tienes instaladas las dependencias necesarias
+si no lo estan las instalara. despues clonara el repositorio con los temas en tu directorio HOME. 
+Despues de esto hara un backup de tus archivos de configuracion y copiara los de los nuevos temas.
+Te pedira acceso como root para poder cambiar tu shell por defecto a zsh por si no lo tubieras intalado. 
+Este script no tiene potencial para romper tu sistema, solo realiza modificaciones del aspecto visual.${end}"
 
 while true; do
-	read -rp " Do you wish to continue? [y/N]: " yn
+	read -rp " Quieres continuar? [y/N]: " yn
 		case $yn in
 			[Yy]* ) break;;
 			[Nn]* ) exit;;
@@ -50,7 +88,8 @@ clear
 
 ########## ---------- Install packages ---------- ##########
 
-logo "Installing needed packages.."
+logo 
+echo -e "${gray}Instalando paquetes necesarios...${end}"
 
 dependencias=(build-essential libgtk-3-dev libdbusmenu-glib-dev libdbusmenu-gtk3-dev \
 			  bspwm polybar sxhkd brightnessctl dunst rofi picom xdo xdotool jgmenu \
@@ -62,20 +101,19 @@ dependencias=(build-essential libgtk-3-dev libdbusmenu-glib-dev libdbusmenu-gtk3
 			  kitty lsd bat micro zsh )
 
 is_installed() {
-  dpkg -l "$1" &> /dev/null
-  return $?
+    dpkg -l "$1" &> /dev/null
+    return $?
 }
-
-printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
+echo -e "${blue}[*] ${gray}Comprobando paquetes requeridos...\n${end}"
 for paquete in "${dependencias[@]}"
 do
-  if ! is_installed "$paquete"; then
+if ! is_installed "$paquete"; then
     sudo apt-get install -qq -y "$paquete" 
-    printf "\n"
-  else
-    printf '%s%s is already installed on your system!%s\n' "${CGR}" "$paquete" "${CNC}"
+    echo -e "\n"
+else
+    echo -e "${green}[+] ${gray}$paquete ya esta instalado en tu sistema.${end}"
     sleep 0.5
-  fi
+fi
 done
 sleep 0.5
 clear
@@ -84,29 +122,28 @@ clear
 ########## ---------- Preparing Folders ---------- ##########
 
 # Verifica si el archivo user-dirs.dirs no existe en ~/.config
-	if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then
-		xdg-user-dirs-update
-		echo "Creating xdg-user-dirs"
-	fi
+if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then
+	xdg-user-dirs-update
+	echo "${gren}[+} ${gray}Creando directorios de usuario${end}"
+fi
 sleep 0.5
 clear
 
 ########## ---------- Cloning the Rice! ---------- ##########
-sudo apt install -y stow
-
-logo "Downloading dotfiles"
+logo 
+echo -e "Descargando dotfiles"
 
 repo_url="https://github.com/boltercio/dotfiles"
 repo_dir="$HOME/.dotfiles"
 
 # Verifica si el directorio del repositorio ya existe y, si es así, lo elimina
-	if [ -d "$repo_dir" ]; then
-		printf "Removing existing dotfiles repository\n"
-		rm -rf "$repo_dir"
-	fi
+if [ -d "$repo_dir" ]; then
+	echo -e "${red}[!} ${gray}Removing existing dotfiles repository\n${end}"
+	rm -rf "$repo_dir"
+fi
 
 # Clona el repositorio
-printf "Cloning dotfiles from %s\n" "$repo_url"
+echo -e "Clonando archivos desde $repo_url\n"
 git clone --depth=1 "$repo_url" "$repo_dir"
 cd $repo_dir
 stow -v .
@@ -130,39 +167,42 @@ sudo mv zsh* /usr/share/zsh/plugins/
 
 ########## ---------- Installing tdrop,eww,xqp & stalonetray ---------- ##########
 
-logo "installing EWW"
+logo 
+echo -e "instalando EWW"
 # Installing Eww
-	if command -v eww >/dev/null 2>&1; then 
-		printf "\n%s%sEww is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
-	else
-		printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
-		{
-			sudo apt install curl
-			cd "$HOME" || exit
-			git clone https://github.com/elkowar/eww
-			cd eww || exit
-			curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-			. "$HOME/.cargo/env"
-			cargo build --release --no-default-features --features x11
-			sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
-		} && {
-			cd "$HOME" || exit
-			rm -rf {.cargo,.rustup,eww}
-		} || {
-        printf "\n%s%sFailed to install Eww. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+if command -v eww >/dev/null 2>&1; then 
+	echo -e "${green}[+] ${gray}Eww is already installed\n${end}"
+else
+	echo -e "${green}[+] ${gray}Instalando Eww, esto puede tardar unos 10 minutos.\n${end}"
+	{
+	sudo apt install curl
+		cd "$HOME" || exit
+		git clone https://github.com/elkowar/eww
+		cd eww || exit
+		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+		. "$HOME/.cargo/env"
+		cargo build --release --no-default-features --features x11
+		sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
+	} && {
+		cd "$HOME" || exit
+	    rm -rf {.cargo,.rustup,eww}
+    } || {
+        echo -e "${red}[!] ${gray}Fallo al installar Eww. tendras que instalarlo manualmente.\n"
+        sleep 2 
     }
-	fi
+fi
 
 ########## --------- Changing shell to zsh ---------- ##########
 
-logo "Changing default shell to zsh"
+logo 
+echo -e "Cambiando shell predeterminada a zsh"
 
-	if [[ $SHELL != "/usr/bin/zsh" ]]; then
-		printf "\n%s%sChanging your shell to zsh. Your root password is needed.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
-		# Cambia la shell a zsh
-		chsh -s /usr/bin/zsh
-		printf "%s%sShell changed to zsh. Please reboot.%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-	else
-		printf "%s%sYour shell is already zsh\nGood bye! installation finished, now reboot%s\n" "${BLD}" "${CGR}" "${CNC}"
-	fi
+if [[ $SHELL != "/usr/bin/zsh" ]]; then
+	echo -e "${green}[+] ${gray}Cambiando tu shell a zsh. se necesita acceso root${end}"
+	# Cambia la shell a zsh
+	chsh -s /usr/bin/zsh
+	echo -e "${green}[+] ${gray}Shell cambiada a zsh. Por favor reinicia el sistema.${end}"
+else
+	echo -e "${green}[+] ${gray}Zsh ya es tu shell por defecto."
+fi
 zsh
